FROM trivadis/spark-template-maven:3.5.0

LABEL MAINTAINER="Guido Schmutz <schmutz68@gmail.com>"

ENV SPARK_APPLICATION_JAR_NAME Docker-Maven-Template-0.1.0-SNAPSHOT
ENV SPARK_APPLICATION_MAIN_CLASS eu.bde.template.maven.WordCount
ENV SPARK_APPLICATION_ARGS "/home/bitnami/spark/README.md"